// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebCarsProject.Data;

namespace WebCarsProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210111084734_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("WebCarsProject.Data.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mercedes"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Peugeot"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Opel"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Skoda"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Mitsubishi"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Mitsubishi"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Toyota"
                        });
                });

            modelBuilder.Entity("WebCarsProject.Data.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<string>("CarPic")
                        .HasColumnType("text");

                    b.Property<int>("ColorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FuelId")
                        .HasColumnType("integer");

                    b.Property<int>("Horsepower")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<int>("Km")
                        .HasColumnType("integer");

                    b.Property<int>("LikesCount")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("TransmissionId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.HasIndex("FuelId");

                    b.HasIndex("TransmissionId");

                    b.HasIndex("UserId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CarPic = "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/10best-cars-group-cropped-1542126037.jpg",
                            ColorId = 1,
                            CreatedTime = new DateTime(2021, 1, 11, 8, 47, 34, 345, DateTimeKind.Utc).AddTicks(8079),
                            FuelId = 1,
                            Horsepower = 100,
                            IsAvailable = true,
                            Km = 70000,
                            LikesCount = 0,
                            Model = "M235i",
                            Price = 99000.0,
                            TransmissionId = 1,
                            UserId = 1,
                            ViewCount = 0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            CarPic = "https://g1-bg.cars.bg/2020-07-14_2/5f0ddd0737b7786f0443bd62o.jpg",
                            ColorId = 2,
                            CreatedTime = new DateTime(2021, 1, 11, 8, 47, 34, 346, DateTimeKind.Utc).AddTicks(4014),
                            FuelId = 3,
                            Horsepower = 101,
                            IsAvailable = true,
                            Km = 178000,
                            LikesCount = 0,
                            Model = "320",
                            Price = 8000.0,
                            TransmissionId = 2,
                            UserId = 2,
                            ViewCount = 0,
                            Year = 2006
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 5,
                            CarPic = "https://g1-bg.cars.bg/2020-08-24_2/5f43bca61b09d640386585d2b.jpg",
                            ColorId = 2,
                            CreatedTime = new DateTime(2021, 1, 11, 8, 47, 34, 346, DateTimeKind.Utc).AddTicks(4142),
                            FuelId = 3,
                            Horsepower = 101,
                            IsAvailable = true,
                            Km = 91000,
                            LikesCount = 0,
                            Model = "3008",
                            Price = 39999.0,
                            TransmissionId = 2,
                            UserId = 2,
                            ViewCount = 0,
                            Year = 2017
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            CarPic = "https://g1-bg.cars.bg/2020-11-09_2/5fa95efcdf6eec09ae410d12b.jpg",
                            ColorId = 2,
                            CreatedTime = new DateTime(2021, 1, 11, 8, 47, 34, 346, DateTimeKind.Utc).AddTicks(4168),
                            FuelId = 3,
                            Horsepower = 150,
                            IsAvailable = true,
                            Km = 286000,
                            LikesCount = 0,
                            Model = "E60",
                            Price = 16700.0,
                            TransmissionId = 1,
                            UserId = 2,
                            ViewCount = 0,
                            Year = 2009
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            CarPic = "https://g1-bg.cars.bg/2020-07-06_2/5f0352cd072750288a141af2b.jpg",
                            ColorId = 3,
                            CreatedTime = new DateTime(2021, 1, 11, 8, 47, 34, 346, DateTimeKind.Utc).AddTicks(4190),
                            FuelId = 1,
                            Horsepower = 160,
                            IsAvailable = true,
                            Km = 76000,
                            LikesCount = 0,
                            Model = "320",
                            Price = 25300.0,
                            TransmissionId = 1,
                            UserId = 2,
                            ViewCount = 0,
                            Year = 2015
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 3,
                            CarPic = "https://g1-bg.cars.bg/2020-11-22_2/5fba75c4d87c677584246302o.jpg",
                            ColorId = 5,
                            CreatedTime = new DateTime(2021, 1, 11, 8, 47, 34, 346, DateTimeKind.Utc).AddTicks(4216),
                            FuelId = 3,
                            Horsepower = 170,
                            IsAvailable = true,
                            Km = 235000,
                            LikesCount = 0,
                            Model = "C 220",
                            Price = 9000.0,
                            TransmissionId = 2,
                            UserId = 3,
                            ViewCount = 0,
                            Year = 2007
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 3,
                            CarPic = "https://g1-bg.cars.bg/2017-11-28_1/17824566o.jpg",
                            ColorId = 10,
                            CreatedTime = new DateTime(2021, 1, 11, 8, 47, 34, 346, DateTimeKind.Utc).AddTicks(4237),
                            FuelId = 3,
                            Horsepower = 170,
                            IsAvailable = true,
                            Km = 188000,
                            LikesCount = 0,
                            Model = "C 220",
                            Price = 27900.0,
                            TransmissionId = 1,
                            UserId = 2,
                            ViewCount = 0,
                            Year = 2014
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 3,
                            CarPic = "https://g1-bg.cars.bg/2020-06-23_2/5ef1c5866d1c2d269e2cbc14o.jpg",
                            ColorId = 1,
                            CreatedTime = new DateTime(2021, 1, 11, 8, 47, 34, 346, DateTimeKind.Utc).AddTicks(4258),
                            FuelId = 3,
                            Horsepower = 204,
                            IsAvailable = true,
                            Km = 26000,
                            LikesCount = 0,
                            Model = "GLC 250",
                            Price = 95000.0,
                            TransmissionId = 1,
                            UserId = 2,
                            ViewCount = 0,
                            Year = 2017
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 3,
                            CarPic = "https://g1-bg.cars.bg/2020-05-24_2/5eca6436267dcc48fc0eedb2o.jpg",
                            ColorId = 5,
                            CreatedTime = new DateTime(2021, 1, 11, 8, 47, 34, 346, DateTimeKind.Utc).AddTicks(4279),
                            FuelId = 2,
                            Horsepower = 333,
                            IsAvailable = true,
                            Km = 84000,
                            LikesCount = 0,
                            Model = "E 400",
                            Price = 84900.0,
                            TransmissionId = 1,
                            UserId = 2,
                            ViewCount = 0,
                            Year = 2017
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 3,
                            CarPic = "https://g1-bg.cars.bg/2020-08-02_2/5f27262e9a1ae76752044183o.jpg",
                            ColorId = 2,
                            CreatedTime = new DateTime(2021, 1, 11, 8, 47, 34, 346, DateTimeKind.Utc).AddTicks(4406),
                            FuelId = 2,
                            Horsepower = 500,
                            IsAvailable = true,
                            Km = 155000,
                            LikesCount = 0,
                            Model = "C 63",
                            Price = 59900.0,
                            TransmissionId = 1,
                            UserId = 2,
                            ViewCount = 0,
                            Year = 2010
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 3,
                            CarPic = "https://g1-bg.cars.bg/2020-11-18_1/5fb47bb365020349af41da42o.jpg",
                            ColorId = 6,
                            CreatedTime = new DateTime(2021, 1, 11, 8, 47, 34, 346, DateTimeKind.Utc).AddTicks(4429),
                            FuelId = 2,
                            Horsepower = 510,
                            IsAvailable = true,
                            Km = 25000,
                            LikesCount = 0,
                            Model = "GT",
                            Price = 174999.0,
                            TransmissionId = 1,
                            UserId = 3,
                            ViewCount = 0,
                            Year = 2016
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 4,
                            CarPic = "https://g1-bg.cars.bg/2020-06-06_2/5edb8a8f752df425d624b483o.jpg",
                            ColorId = 5,
                            CreatedTime = new DateTime(2021, 1, 11, 8, 47, 34, 346, DateTimeKind.Utc).AddTicks(4449),
                            FuelId = 3,
                            Horsepower = 150,
                            IsAvailable = true,
                            Km = 167000,
                            LikesCount = 0,
                            Model = "Accord",
                            Price = 15800.0,
                            TransmissionId = 2,
                            UserId = 3,
                            ViewCount = 0,
                            Year = 2010
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 4,
                            CarPic = "https://g1-bg.cars.bg/2019-08-02_2/31305837o.jpg",
                            ColorId = 5,
                            CreatedTime = new DateTime(2021, 1, 11, 8, 47, 34, 346, DateTimeKind.Utc).AddTicks(4470),
                            FuelId = 2,
                            Horsepower = 161,
                            IsAvailable = true,
                            Km = 40181,
                            LikesCount = 0,
                            Model = "Civic ",
                            Price = 26750.0,
                            TransmissionId = 1,
                            UserId = 3,
                            ViewCount = 0,
                            Year = 2017
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 4,
                            CarPic = "https://g1-bg.cars.bg/2020-04-07_2/5e8c8f30794ff050e3105964o.jpg",
                            ColorId = 5,
                            CreatedTime = new DateTime(2021, 1, 11, 8, 47, 34, 346, DateTimeKind.Utc).AddTicks(4489),
                            FuelId = 2,
                            Horsepower = 182,
                            IsAvailable = true,
                            Km = 23000,
                            LikesCount = 0,
                            Model = "Civic ",
                            Price = 39900.0,
                            TransmissionId = 1,
                            UserId = 3,
                            ViewCount = 0,
                            Year = 2018
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 4,
                            CarPic = "https://g1-bg.cars.bg/2020-10-16_1/5f895bf06cb0a84db67d7fb2o.jpg",
                            ColorId = 1,
                            CreatedTime = new DateTime(2021, 1, 11, 8, 47, 34, 346, DateTimeKind.Utc).AddTicks(4509),
                            FuelId = 3,
                            Horsepower = 160,
                            IsAvailable = true,
                            Km = 75600,
                            LikesCount = 0,
                            Model = "CR-v",
                            Price = 46990.0,
                            TransmissionId = 1,
                            UserId = 3,
                            ViewCount = 0,
                            Year = 2015
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 5,
                            CarPic = "https://g1-bg.cars.bg/2020-10-31_1/5f9cd80b8f564d2c9926e5e2o.jpg",
                            ColorId = 1,
                            CreatedTime = new DateTime(2021, 1, 11, 8, 47, 34, 346, DateTimeKind.Utc).AddTicks(4529),
                            FuelId = 2,
                            Horsepower = 225,
                            IsAvailable = true,
                            Km = 62000,
                            LikesCount = 0,
                            Model = "508",
                            Price = 66000.0,
                            TransmissionId = 1,
                            UserId = 2,
                            ViewCount = 0,
                            Year = 2019
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 11,
                            CarPic = "https://g1-bg.cars.bg/2020-09-11_1/5f5b210107c8b8427b4ee022o.jpg",
                            ColorId = 10,
                            CreatedTime = new DateTime(2021, 1, 11, 8, 47, 34, 346, DateTimeKind.Utc).AddTicks(4550),
                            FuelId = 4,
                            Horsepower = 218,
                            IsAvailable = true,
                            Km = 4000,
                            LikesCount = 0,
                            Model = "Camry",
                            Price = 67990.0,
                            TransmissionId = 1,
                            UserId = 2,
                            ViewCount = 0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 1,
                            CarPic = "https://g1-bg.cars.bg/2020-11-13_2/5fae87399b9c727e493ad622b.jpg",
                            ColorId = 3,
                            CreatedTime = new DateTime(2021, 1, 11, 8, 47, 34, 346, DateTimeKind.Utc).AddTicks(4571),
                            FuelId = 1,
                            Horsepower = 140,
                            IsAvailable = true,
                            Km = 180000,
                            LikesCount = 0,
                            Model = "530",
                            Price = 21300.0,
                            TransmissionId = 2,
                            UserId = 2,
                            ViewCount = 0,
                            Year = 2011
                        });
                });

            modelBuilder.Entity("WebCarsProject.Data.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 2,
                            Name = "White"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Blue"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Green "
                        },
                        new
                        {
                            Id = 5,
                            Name = "Grey"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Yellow"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pink"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Brown"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Purple"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Black"
                        });
                });

            modelBuilder.Entity("WebCarsProject.Data.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("WebCarsProject.Data.Fuel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Fuels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "LPG"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Petrol"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Diesel"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hybrid"
                        });
                });

            modelBuilder.Entity("WebCarsProject.Data.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("WebCarsProject.Data.RequestSaver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<string>("Protocol")
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Verb")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RequestSavers");
                });

            modelBuilder.Entity("WebCarsProject.Data.Transmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Transmissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Automatic"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Manual"
                        });
                });

            modelBuilder.Entity("WebCarsProject.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PicPath")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<int>("UserTypeID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserTypeID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ivan@abv.bg",
                            FirstName = "Ivan",
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ivanov",
                            Password = "123456",
                            Phone = "0877585858",
                            PicPath = "https://st2.depositphotos.com/2498595/6618/v/950/depositphotos_66187233-stock-illustration-profile-outline-symbol-dark-on.jpg",
                            UserName = "ivan777",
                            UserTypeID = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "pesho@gmai.com",
                            FirstName = "Peho",
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Petrov",
                            Password = "123456",
                            Phone = "0877587777",
                            PicPath = "https://www.pavilionweb.com/wp-content/uploads/2017/03/man-300x300.png",
                            UserName = "pesho123",
                            UserTypeID = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "gosho321@gmai.com",
                            FirstName = "Gosho",
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Georgiev",
                            Password = "123456",
                            Phone = "0877587777",
                            PicPath = "https://img.icons8.com/bubbles/2x/user-male.png",
                            UserName = "gosho321",
                            UserTypeID = 2
                        });
                });

            modelBuilder.Entity("WebCarsProject.Data.UserType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("TypeOfUser")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TypeOfUser = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            TypeOfUser = "User"
                        });
                });

            modelBuilder.Entity("WebCarsProject.Data.Car", b =>
                {
                    b.HasOne("WebCarsProject.Data.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCarsProject.Data.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCarsProject.Data.Fuel", "Fuel")
                        .WithMany()
                        .HasForeignKey("FuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCarsProject.Data.Transmission", "Transmission")
                        .WithMany()
                        .HasForeignKey("TransmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCarsProject.Data.User", "User")
                        .WithMany("Cars")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebCarsProject.Data.Comment", b =>
                {
                    b.HasOne("WebCarsProject.Data.Car", "Car")
                        .WithMany("Comments")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCarsProject.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebCarsProject.Data.Like", b =>
                {
                    b.HasOne("WebCarsProject.Data.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCarsProject.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebCarsProject.Data.User", b =>
                {
                    b.HasOne("WebCarsProject.Data.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
